### ISSUE TITLE
Links to dtorg don't show decent image/title/description etc.

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtorg#176]
I tried to include a link to darktable.org on my LinkedIn profile and it doesn't show a preview image. The title it picks up is "by photographers" and the description is "darktable is created for photographers, by photographers . Having developers that are also avid photographers as part of the target audience is good for understanding the real world problems, challenges, and workflows. darktable edits your images...".

It would be nice to include some metadata so that this stuff populates correctly when linking from external sites.

Some googling suggests that LinkedIn (for example) needs the following:

```
<meta property='og:title' content='Title of the article"/>
<meta property='og:image' content='//media.example.com/ 1234567.jpg"/>
<meta property='og:description' content='Description that will show in the preview"/>
<meta property='og:url' content='//www.example.com/URL of the article" />
```

**Comment by elstoc** [comment]
This [link to stackoverflow](https://stackoverflow.com/questions/1092329/what-are-the-important-meta-tags-i-must-put-in-my-website) has some useful suggestions for various sites.

**Comment by patdavid** [comment]
Weird.  I thought I had included metadata like this in the templates but it might have either gotten lost in the hugo transition or I just didn't actually do it... :)

This isn't very hard to add - just need to find time to do it (it's on LibreArts.org for instance already - we might be able to borrow the metadata partial from there).

**Comment by patdavid** [comment]
I stole the opengraph.html layout from librearts and wired it up here in commit: https://github.com/darktable-org/dtorg/commit/92f48d2dab9fd4ceb3e88332b556a845bbd856a6.

I had to add a couple of lines in the config.yaml file to add a `description` and `Logo` key - change as desired.

**Comment by elstoc** [comment]
As discussed it needs a better image as the current one just comes up as white-on-white on LinkedIn perhaps https://github.com/darktable-org/dtdocs/blob/master/static/darktable-logo.svg

**Comment by patdavid** [comment]
Ok, I've just pushed a commit (https://github.com/darktable-org/dtorg/commit/36fc1e4e3210c9f4dbf1d9e6dd014c4da44ee923) to swap out that image with a PNG version of just the logo at 512px.

**Comment by elstoc** [comment]
still shows the same image -- see https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.darktable.org

I think this requires the og.image meta property
